### ISSUE TITLE
Maya 2022 build errors

### ISSUE THREAD

**Issue by swnolan** [robertjoosten/maya-dem-bones#1]
Hi Robert,
First, thank you for building this project! Very cool and super helpful!

So I got Maya 2020 to build ok. A couple of errors but built successfully. 

Maya 2022 not as much. I'm currently still using Python 2.7 with this version. Eventually making the shift over to 3.7. 

I modified the build.bat to see if I could get a 2.7 build but this didn't work. 
if "%maya_version%"=="2022" (
    set python_export="init_dem_bones"
    set python_lib=python27.lib
    set python_include=Python27\Python
    set vs_directory="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\"
)
Any suggestions?

Even with Python37 the build fails: _dem_bones.pyd : fatal error LNK1120: 202 unresolved externals

Also, couldn't run this with a normal cmd prompt. Only works if I used the VS Dev Command Prompt.
Cheers,
-Sean

**Comment by robertjoosten** [comment]
Hi Sean,

I am unable to replicate this unfortunately.
I've modified the bat file just like you did. 
Running the bat builds a pyd file that works when using Maya 2022 in its python 2 environment.
What behaviour are you seeing when running the bat through a normal command prompt?

```
if "%maya_version%"=="2022" (
    set python_export="init_dem_bones"
    set python_lib=python27.lib
    set python_include=Python27\Python
    set vs_directory="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\"
)
```

**Comment by swnolan** [comment]
Hi Robert,
Thanks for quick the response. Ok, was able to generate and pyd for 2022 with Py27. I must have tried to run CMD not in admin mode.  Doh! User error on my part. 

I'm not getting 'errors', just 'warnings' instead:

maya-dem-bones\src\main.cpp(195): warning C4996: 'Autodesk::Maya::OpenMaya20220000::MFnDependencyNode::findPlug': Use the MFnDependencyNode::findPlug( const MString&, bool, MStatus* ) method instead.
maya-dem-bones\src\main.cpp(233): warning C4996: 'Autodesk::Maya::OpenMaya20220000::MFnDependencyNode::findPlug': Use the MFnDependencyNode::findPlug( const MString&, bool, MStatus* ) method instead.
maya-dem-bones\src\main.cpp(254): warning C4996: 'Autodesk::Maya::OpenMaya20220000::MFnDependencyNode::findPlug': Use the MFnDependencyNode::findPlug( const MString&, bool, MStatus* ) method instead.
maya-dem-bones\src\main.cpp(287): warning C4996: 'Autodesk::Maya::OpenMaya20220000::MFnDependencyNode::findPlug': Use the MFnDependencyNode::findPlug( const MString&, bool, MStatus* ) method instead.
