### ISSUE TITLE
Question about add new joints on exsiting joints

### ISSUE THREAD

**Issue by snowzhangy** [robertjoosten/maya-dem-bones#4]
Hi Robert:
   I have a question regarding to the dembones. If i already have exsiting joints and would like to add another 10 joints  to get better result. How can i do that?
  I tried simply add nB by 10 but compute will call  init() first and will return nB to 1 since the m and w matrix will not equal to nB anymore. Did i missing anything? hope you could help me .
 Thank you

Yang

**Comment by snowzhangy** [comment]
already solved

**Comment by BNGame** [comment]
> Hi Robert: I have a question regarding to the dembones. If i already have exsiting joints and would like to add another 10 joints to get better result. How can i do that? I tried simply add nB by 10 but compute will call init() first and will return nB to 1 since the m and w matrix will not equal to nB anymore. Did i missing anything? hope you could help me . Thank you
> 
> Yang

Hi Yang,

Sorry I reply here, I'm 3d modeler artist and not familiar too much with script, can you help me I install this script? I followed the instructions but I got an error when I used in Maya .
